# Generated by Django 5.2.6 on 2025-09-24 13:31

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productcolor",
            name="color_code",
            field=colorfield.fields.ColorField(
                blank=True,
                default=None,
                image_field=None,
                max_length=7,
                null=True,
                samples=None,
            ),
        ),
    ]
