# Generated by Django 5.2.6 on 2025-09-24 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_alter_productcolor_color_code"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="color",),
        migrations.AlterField(
            model_name="productcolor",
            name="color_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
