# Generated by Django 5.2.6 on 2025-09-28 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_add_missing_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="primary_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="primary_products",
                to="store.category",
            ),
        ),
    ]
