# Generated by Django 5.2.6 on 2025-09-28 16:30

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_alter_product_primary_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="primary_brand_or_type",
            field=smart_selects.db_fields.ChainedForeignKey(
                auto_choose=True,
                blank=True,
                chained_field="primary_sub_category",
                chained_model_field="sub_category",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="primary_products",
                to="store.brandsortypesofsubcategory",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="primary_sub_category",
            field=smart_selects.db_fields.ChainedForeignKey(
                auto_choose=True,
                blank=True,
                chained_field="primary_category",
                chained_model_field="category",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="primary_products",
                to="store.subcategory",
            ),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="brand_or_type",
            field=smart_selects.db_fields.ChainedForeignKey(
                auto_choose=True,
                blank=True,
                chained_field="sub_category",
                chained_model_field="sub_category",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="productcategory_brands_or_types",
                to="store.brandsortypesofsubcategory",
            ),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="sub_category",
            field=smart_selects.db_fields.ChainedForeignKey(
                auto_choose=True,
                blank=True,
                chained_field="category",
                chained_model_field="category",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="productcategory_subcategories",
                to="store.subcategory",
            ),
        ),
    ]
