# Generated by Django 5.2.6 on 2025-09-25 11:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_remove_product_color_alter_productcolor_color_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="category_adding_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="category",
            name="display_at_bar",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="category",
            name="serial",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
