# Generated by Django 5.2.6 on 2025-09-28 19:48

import django.db.models.deletion
import smart_selects.db_fields
import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_alter_product_primary_brand_or_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="primary_brand_or_type",
            field=smart_selects.db_fields.ChainedForeignKey(
                auto_choose=True,
                blank=True,
                chained_field="primary_sub_category",
                chained_model_field="sub_category",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="primary_products",
                to="store.brandsortypesofsubcategory",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="primary_category",
            field=models.ForeignKey(
                blank=True,
                default=21,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="primary_products",
                to="store.category",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="primary_sub_category",
            field=smart_selects.db_fields.ChainedForeignKey(
                auto_choose=True,
                blank=True,
                chained_field="primary_category",
                chained_model_field="category",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="primary_products",
                to="store.subcategory",
            ),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="brand_or_type",
            field=smart_selects.db_fields.ChainedForeignKey(
                auto_choose=True,
                blank=True,
                chained_field="sub_category",
                chained_model_field="sub_category",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="productcategory_brands_or_types",
                to="store.brandsortypesofsubcategory",
            ),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="category",
            field=models.ForeignKey(
                default=21,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="store.category",
            ),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="sub_category",
            field=smart_selects.db_fields.ChainedForeignKey(
                auto_choose=True,
                blank=True,
                chained_field="category",
                chained_model_field="category",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="productcategory_subcategories",
                to="store.subcategory",
            ),
        ),
    ]
