# Generated by Django 5.2.6 on 2025-09-26 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_attribute_attributevalue_variant_variantcolorstock"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="sub_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="store.subcategory",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="types_of_sub_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="store.typesofsubcategory",
            ),
        ),
    ]
