# Generated by Django 5.2.6 on 2025-09-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_product_sub_category_product_types_of_sub_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subcategory",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="typesofsubcategory",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
