# Generated by Django 5.2.6 on 2025-09-28 20:09

import django.db.models.deletion
import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_alter_product_primary_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="primary_category",
            field=models.ForeignKey(
                blank=True,
                default=21,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="primary_products",
                to="store.category",
            ),
        ),
    ]
