# Generated by Django 5.2.6 on 2025-09-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_alter_subcategory_name_alter_typesofsubcategory_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subcategory",
            name="name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="typesofsubcategory",
            name="name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
