# Generated by Django 5.2.6 on 2025-09-29 06:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0008_alter_productcategory_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_adding_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
