# Generated by Django 5.2.6 on 2025-09-26 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0009_alter_subcategory_name_alter_typesofsubcategory_name"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="category",),
        migrations.RemoveField(model_name="product", name="sub_category",),
        migrations.RemoveField(model_name="product", name="types_of_sub_category",),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ManyToManyField(related_name="products", to="store.category"),
        ),
        migrations.AddField(
            model_name="product",
            name="sub_category",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="store.subcategory"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="types_of_sub_category",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="store.typesofsubcategory"
            ),
        ),
    ]
