# Generated by Django 5.2.6 on 2025-09-29 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0009_alter_product_product_adding_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(
                max_length=250, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
