# Generated by Django 5.2.6 on 2025-09-29 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0010_alter_product_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(
                blank=True,
                max_length=250,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
