# Generated by Django 5.2.6 on 2025-09-29 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0012_alter_product_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
    ]
