# Generated by Django 5.2.6 on 2025-09-29 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0013_product_id_alter_product_slug"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="id",),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(
                blank=True,
                max_length=250,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
