# Generated by Django 5.2.6 on 2025-09-29 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0015_product_id_alter_product_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="primary_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="primary_products",
                to="store.category",
            ),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="store.category",
            ),
        ),
    ]
