# Generated by Django 5.2.6 on 2025-09-29 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0016_alter_product_primary_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="primary_category",
            field=models.ForeignKey(
                blank=True,
                default=21,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="primary_products",
                to="store.category",
            ),
        ),
    ]
