# Generated by Django 5.2.6 on 2025-10-03 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0018_alter_product_primary_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="brandsortypesofsubcategory",
            options={"verbose_name_plural": "Brands or Types of Sub Categories"},
        ),
        migrations.AddField(
            model_name="brandsortypesofsubcategory",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="Brands or Types of Sub Categories/"
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="Categories/"),
        ),
        migrations.AddField(
            model_name="subcategory",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="Sub Categories/"),
        ),
    ]
