# Generated by Django 5.2.6 on 2025-09-28 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("outlet", models.CharField(default="All Outlet", max_length=200)),
                ("image", models.ImageField(upload_to="offers/")),
                (
                    "button_text",
                    models.CharField(default="View Details", max_length=50),
                ),
                ("button_link", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["-start_date"],},
        ),
    ]
