# Generated by Django 5.2.6 on 2025-10-03 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="image",
            field=models.ImageField(upload_to="Offers/"),
        ),
    ]
