# Generated by Django 4.2.24 on 2025-09-13 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="shipping",
            field=models.DecimalField(decimal_places=2, default=60, max_digits=10),
        ),
    ]
