# Generated by Django 4.2.24 on 2025-09-14 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_order_completed_orderitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="shipping",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="order",
            name="subtotal",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="order",
            name="total",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
